{% set version = "0.3.2" %}

package:
  name: auto-optional
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/auto-optional/auto-optional-{{ version }}.tar.gz
  sha256: dcd2af973badd67a89f1bef021a50b298882fc95935739a8818b43c5942118d8

build:
  entry_points:
    - auto-optional = auto_optional.main:app
  noarch: python
  script:
    - sed -i 's/libcst = "^/libcst = ">=/' pyproject.toml
    - sed -i 's/typer = "^/typer = ">=/' pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - sed
  host:
    - python ={{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - libcst
    - typer

test:
  imports:
    - auto_optional
  commands:
    - pip check
    - auto-optional --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://auto-optional.daanluttik.nl
  summary: Adds the Optional type-hint to arguments where the default value is None
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
